In [1]:
import pandas as pd
import seaborn as sns

# 예제 데이터셋

In [2]:
# seaborn 패키지에서 제공하는 tips 데이터셋을 불러와서 DataFrame을 생성.
tips = sns.load_dataset('tips')

In [3]:
print(type(tips))

<class 'pandas.core.frame.DataFrame'>

In [4]:
tips.head()  # DF의 첫 5개 행을 출력 tips.iloc[:5]와 같음.

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# 연습문제

*   DataFrame의 행과 열의 개수
*   열(column) 이름들
*   마지막 6개 행을 출력
*   DataFrame의 요약 정보
*   숫자 타입 변수(컬럼)의 기술 통계량
*   카테고리 타입 변수의 빈도수
*   total_bill 컬럼의 값이 최댓값인 행을 출력
*   total_bill 컬럼의 값이 최솟값인 행을 출력
*   남성들의 tip의 평균
*   여성들의 tip의 평균
*   일요일의 tip의 평균
*   일요일 남성의 tip의 평균
*   일요일 여성의 tip의 평균

In [6]:
# DataFrame의 행과 열의 개수
tips.shape

(244, 7)

In [36]:
print('행의 개수:', tips.shape[0])
print('열의 개수:', tips.shape[1])

행의 개수: 244
열의 개수: 7

In [8]:
# 열(column)이름들
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [37]:
for c in tips.columns:  # Index 객체는 for-in 반복문에서 사용 가능.
    print(c)

total_bill
tip
sex
smoker
day
time
size

In [38]:
# 마지막 6개 행을 출력
# tips.iloc[-6:]
tips.tail(n=6)

     total_bill   tip     sex smoker   day    time  size
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [10]:
# DataFrame의 요약정보
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [11]:
# 숫자 타입 변수(컬럼)의 기술 통계량
# 기술 통계량: non-null 자료 개수, 합계, 평균, 표준편차, 최댓값, 최솟값, ...
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [17]:
# 카테고리 타입 변수의 빈도수
tips.sex.value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [19]:
# 카테고리 타입 변수의 빈도수
tips.smoker.value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [21]:
# 카테고리 타입 변수의 빈도수
tips.day.value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [44]:
# 카테고리 타입 변수의 빈도수
tips.time.value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [46]:
# tips.size.value_counts()
# tips.size
# 인원수의 빈도수
tips["size"].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [26]:
# total_bill 컬럼의 값이 최댓값인 행을 출력
tips.loc[tips.total_bill == tips.total_bill.max()]

     total_bill   tip   sex smoker  day    time  size
170       50.81  10.0  Male    Yes  Sat  Dinner     3

In [28]:
# total_bill 컬럼의 값이 최솟값인 행을 출력
tips.loc[tips.total_bill == tips.total_bill.min()]

    total_bill  tip     sex smoker  day    time  size
67        3.07  1.0  Female    Yes  Sat  Dinner     1

In [47]:
tips[(tips.total_bill == tips.total_bill.max()) |
     (tips.total_bill == tips.total_bill.min())]

     total_bill   tip     sex smoker  day    time  size
67         3.07   1.0  Female    Yes  Sat  Dinner     1
170       50.81  10.0    Male    Yes  Sat  Dinner     3

In [31]:
# 남성들의 tip의 평균
tips[tips.sex == "Male"].tip.mean()

np.float64(3.0896178343949043)

In [32]:
# 여성들의 tip의 평균
tips[tips.sex == "Female"].tip.mean()

np.float64(2.8334482758620685)

In [33]:
# 일요일의 tip의 평균
tips[tips.day == "Sun"].tip.mean()

np.float64(3.2551315789473687)

In [34]:
# 일요일 남성의 tip의 평균
tips[(tips.day == "Sun") & (tips.sex == "Male")].tip.mean()

np.float64(3.2203448275862065)

In [35]:
# 일요일 여성의 tip의 평균
tips[(tips.day == "Sun") & (tips.sex == "Female")].tip.mean()

np.float64(3.3672222222222223)

In [55]:
# tip의 값이 평균보다 큰 행들을 찾으세요.
# select * from tips where tip > (select avg(tip) from tips);
tips.loc[tips.tip > tips.tip.mean()]

     total_bill   tip     sex smoker   day    time  size
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
7         26.88  3.12    Male     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
232       11.61  3.39    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
243       18.78  3.00  Female     No  Thur  Dinner     2

[121 rows x 7 columns]

# 파생변수

In [56]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [58]:
# 영수증 금액 대비 팁의 비율
tips.tip / tips.total_bill

0      0.059447
1      0.160542
2      0.166587
3      0.139780
4      0.146808
         ...
239    0.203927
240    0.073584
241    0.088222
242    0.098204
243    0.159744
Length: 244, dtype: float64

In [59]:
# 파생변수 추가
tips['tip_ratio'] = tips.tip / tips.total_bill

In [60]:
tips.head()

   total_bill   tip     sex smoker  day    time  size  tip_ratio
0       16.99  1.01  Female     No  Sun  Dinner     2   0.059447
1       10.34  1.66    Male     No  Sun  Dinner     3   0.160542
2       21.01  3.50    Male     No  Sun  Dinner     3   0.166587
3       23.68  3.31    Male     No  Sun  Dinner     2   0.139780
4       24.59  3.61  Female     No  Sun  Dinner     4   0.146808

*   팁/영수증 비율의 평균값
*   팁/영수증 비율이 평균보다 큰 행들
*   팁/영수증 비율이 평균보다 큰 데이터에서 남성/여성의 비율

In [62]:
tips.tip_ratio.mean()

np.float64(0.16080258172250472)

In [81]:
tips.tip_ratio.describe()

count    244.000000
mean       0.160803
std        0.061072
min        0.035638
25%        0.129127
50%        0.154770
75%        0.191475
max        0.710345
Name: tip_ratio, dtype: float64

In [64]:
tips[tips.tip_ratio > tips.tip_ratio.mean()]

     total_bill   tip   sex smoker  day    time  size  tip_ratio
2         21.01  3.50  Male     No  Sun  Dinner     3   0.166587
5         25.29  4.71  Male     No  Sun  Dinner     4   0.186240
6          8.77  2.00  Male     No  Sun  Dinner     2   0.228050
9         14.78  3.23  Male     No  Sun  Dinner     2   0.218539
10        10.27  1.71  Male     No  Sun  Dinner     2   0.166504
..          ...   ...   ...    ...  ...     ...   ...        ...
228       13.28  2.72  Male     No  Sat  Dinner     2   0.204819
231       15.69  3.00  Male    Yes  Sat  Dinner     3   0.191205
232       11.61  3.39  Male     No  Sat  Dinner     2   0.291990
234       15.53  3.00  Male    Yes  Sat  Dinner     2   0.193175
239       29.03  5.92  Male     No  Sat  Dinner     3   0.203927

[107 rows x 8 columns]

In [82]:
df = tips[tips.tip_ratio > tips.tip_ratio.mean()]

In [84]:
df.sex.value_counts()

sex
Male      66
Female    41
Name: count, dtype: int64

In [86]:
# 전체 남성/여성 고객들 중에서 팁-영수증 비율이 평균보다 큰 남성/여성 고객 비율
df.sex.value_counts() / tips.sex.value_counts()

sex
Male      0.420382
Female    0.471264
Name: count, dtype: float64

In [80]:
tips[tips.tip_ratio > tips.tip_ratio.mean()].sex.value_counts().loc["Male"] / tips[tips.tip_ratio > tips.tip_ratio.mean()].sex.value_counts().loc["Female"]

np.float64(1.6097560975609757)

## titanic 데이터셋

In [87]:
titanic = sns.load_dataset('titanic')

In [88]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

titanic 데이터프레임의 컬럼들:

*   survived: 생존 여부(0 = 사망, 1 = 생존)
    *   alive 컬럼과 같은 내용(no = 사망, yes = 생존)
*   pclass: 객실 등급
    *   class 컬럼과 같은 내용(1 = First, 2 = Second, 3 = Third)
*   sex: 성별(male/female)
*   who: 성인남성(man), 성인여성(woman), 어린이(child)
*   adult_male: 성인 남성 여부(True, False)
*   age: 나이
*   sibsp: 동승한 형제자매(siblings) 또는 배우자(spouses) 수
*   parch: 동승한 부모(parents) 또는 자녀(children) 수
*   alone: 동승자 여부(True=동승자없음(혼자)/False=동승자있음(혼자가아님))
*   fare: 운임(탑승권 가격)
*   embarked: 정박지

In [90]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

## 카테고리(범주) 변수 분석

In [93]:
titanic.survived.value_counts()  # 생존여부

survived
0    549
1    342
Name: count, dtype: int64

In [94]:
titanic.alive.value_counts()

alive
no     549
yes    342
Name: count, dtype: int64

In [97]:
titanic.sex.value_counts()  # 성별 빈도수

sex
male      577
female    314
Name: count, dtype: int64

In [101]:
titanic.who.value_counts()  # 성인남성/성인여성/어린이 빈도수

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [104]:
titanic.adult_male.value_counts()  # 성인남성 여부

adult_male
True     537
False    354
Name: count, dtype: int64

In [105]:
titanic.pclass.value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [108]:
titanic["class"].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

성인남성/ 성인여성/ 어린이 생존 비율

In [205]:
# 강사님 답안
# 생존자 데이터만 갖는 데이터프레임
df_alive = titanic[titanic.alive == 'yes']
#titanic[titanic.survived == 1]

In [214]:
df_alive.who.value_counts().sort_index()  # 생존자 성인남성/ 성인여성/ 어린이 숫자

who
child     49
man       88
woman    205
Name: count, dtype: int64

In [226]:
df_alive.who.value_counts() / titanic.who.value_counts()

who
child    0.590361
man      0.163873
woman    0.756458
Name: count, dtype: float64

In [215]:
titanic.who.value_counts().sort_index()  # 전체 성인남성/ 성인여성/ 어린이 숫자

who
child     83
man      537
woman    271
Name: count, dtype: int64

In [227]:
df_alive.who.value_counts() / titanic.who.value_counts()

who
child    0.590361
man      0.163873
woman    0.756458
Name: count, dtype: float64

In [225]:
titanic[(titanic.survived == 1) & (titanic.who == "man")].count().survived / titanic.who.value_counts()["man"]

np.float64(0.16387337057728119)

In [149]:
titanic[(titanic.survived == 1) & (titanic.who == "woman")].count().survived / titanic.who.value_counts()["woman"]

np.float64(0.7564575645756457)

In [162]:
titanic[(titanic.survived == 1) & (titanic.who == "child")].shape[0] / titanic[titanic.who == "child"].shape[0]

0.5903614457831325

객실 등급별 생존 비율

In [230]:
df_alive.pclass.value_counts()  # 각 객실 등급의 생존자 숫자

pclass
1    136
3    119
2     87
Name: count, dtype: int64

In [238]:
titanic.pclass.value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [239]:
df_alive.pclass.value_counts() / titanic.pclass.value_counts()

pclass
1    0.629630
2    0.472826
3    0.242363
Name: count, dtype: float64

In [181]:
titanic[(titanic.pclass == 1) & (titanic.survived == 1)].shape[0] / titanic.pclass.value_counts().loc[1]

np.float64(0.6296296296296297)

In [182]:
titanic[(titanic.pclass == 2) & (titanic.survived == 1)].shape[0] / titanic.pclass.value_counts().loc[2]

np.float64(0.47282608695652173)

In [183]:
titanic[(titanic.pclass == 3) & (titanic.survived == 1)].shape[0] / titanic.pclass.value_counts().loc[3]

np.float64(0.24236252545824846)

각 객실 등급에서 성인남성/ 성인여성/ 어린이 생존 비율

In [240]:
# 생존자 데이터 프레임에서 pclass, who 컬럼 선택
df_alive[['pclass', 'who']]

     pclass    who
1         1  woman
2         3  woman
3         1  woman
8         3  woman
9         2  child
..      ...    ...
875       3  child
879       1  woman
880       2  woman
887       1  woman
889       1    man

[342 rows x 2 columns]

In [241]:
#
df_alive[['pclass', 'who']].value_counts()

pclass  who
1       woman    89
2       woman    60
3       woman    56
1       man      42
3       man      38
        child    25
2       child    19
        man       8
1       child     5
Name: count, dtype: int64

In [243]:
titanic[['pclass', 'who']].value_counts()

pclass  who
3       man      319
1       man      119
3       woman    114
2       man       99
1       woman     91
2       woman     66
3       child     58
2       child     19
1       child      6
Name: count, dtype: int64

In [244]:
df_alive[['pclass', 'who']].value_counts() / titanic[["pclass", 'who']].value_counts()

pclass  who
1       child    0.833333
        man      0.352941
        woman    0.978022
2       child    1.000000
        man      0.080808
        woman    0.909091
3       child    0.431034
        man      0.119122
        woman    0.491228
Name: count, dtype: float64

In [195]:
titanic[(titanic.survived == 1) & (titanic.pclass == 1) & (titanic.who == "man")].shape[0] / titanic[(titanic.pclass == 1) & (titanic.who == "man")].shape[0]

0.35294117647058826

In [196]:
titanic[(titanic.survived == 1) & (titanic.pclass == 1) & (titanic.who == "woman")].shape[0] / titanic[(titanic.pclass == 1) & (titanic.who == "woman")].shape[0]

0.978021978021978

In [197]:
titanic[(titanic.survived == 1) & (titanic.pclass == 1) & (titanic.who == "child")].shape[0] / titanic[(titanic.pclass == 1) & (titanic.who == "child")].shape[0]

0.8333333333333334

In [198]:
titanic[(titanic.survived == 1) & (titanic.pclass == 2) & (titanic.who == "man")].shape[0] / titanic[(titanic.pclass == 2) & (titanic.who == "man")].shape[0]

0.08080808080808081

In [199]:
titanic[(titanic.survived == 1) & (titanic.pclass == 2) & (titanic.who == "woman")].shape[0] / titanic[(titanic.pclass == 2) & (titanic.who == "woman")].shape[0]

0.9090909090909091

In [200]:
titanic[(titanic.survived == 1) & (titanic.pclass == 2) & (titanic.who == "child")].shape[0] / titanic[(titanic.pclass == 2) & (titanic.who == "child")].shape[0]

1.0

In [201]:
titanic[(titanic.survived == 1) & (titanic.pclass == 3) & (titanic.who == "man")].shape[0] / titanic[(titanic.pclass == 3) & (titanic.who == "man")].shape[0]

0.11912225705329153

In [203]:
titanic[(titanic.survived == 1) & (titanic.pclass == 3) & (titanic.who == "woman")].shape[0] / titanic[(titanic.pclass == 3) & (titanic.who == "woman")].shape[0]

0.49122807017543857

In [204]:
titanic[(titanic.survived == 1) & (titanic.pclass == 3) & (titanic.who == "child")].shape[0] / titanic[(titanic.pclass == 3) & (titanic.who == "child")].shape[0]

0.43103448275862066