# Categorical Data 다루기

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(data={
    "user_id": np.arange(1, 11),
    "gender": ["M"]*5 + ["F"]*5,
    "score": np.random.randint(1, 6, size=10)
})

In [3]:
df

   user_id gender  score
0        1      M      1
1        2      M      1
2        3      M      3
3        4      M      3
4        5      M      1
5        6      F      3
6        7      F      3
7        8      F      2
8        9      F      3
9       10      F      4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  10 non-null     int64
 1   gender   10 non-null     object
 2   score    10 non-null     int64
dtypes: int64(2), object(1)
memory usage: 372.0+ bytes

In [5]:
# gender 컬럼을 문자열 타입에서 카테고리 타입으로 변환.
df.gender = df.gender.astype("category")

In [6]:
df

   user_id gender  score
0        1      M      1
1        2      M      1
2        3      M      3
3        4      M      3
4        5      M      1
5        6      F      3
6        7      F      3
7        8      F      2
8        9      F      3
9       10      F      4

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  10 non-null     int64
 1   gender   10 non-null     category
 2   score    10 non-null     int64
dtypes: category(1), int64(2)
memory usage: 426.0 bytes

In [8]:
# Categorical Accessor(카테고리 접근자)
df.gender.cat.categories

Index(['F', 'M'], dtype='object')

# 연속형 변수에서 파상된 카테고리 변수 만들기

In [9]:
df = pd.DataFrame(data={
    "id": np.arange(1, 11),
    "age": np.random.randint(100, size=10)
})

In [10]:
df

   id  age
0   1   93
1   2   44
2   3   51
3   4   26
4   5   73
5   6   39
6   7   87
7   8   98
8   9   44
9  10   70

In [14]:
# age 컬럼의 값을 이용해서 연령대 파생변수를 추가.
df["age_range"] = pd.cut(x=df.age, bins=np.arange(0, 110, 10), right=True)

In [15]:
df

   id  age  age_range
0   1   93  (90, 100]
1   2   44   (40, 50]
2   3   51   (50, 60]
3   4   26   (20, 30]
4   5   73   (70, 80]
5   6   39   (30, 40]
6   7   87   (80, 90]
7   8   98  (90, 100]
8   9   44   (40, 50]
9  10   70   (60, 70]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         10 non-null     int64
 1   age        10 non-null     int64
 2   age_range  10 non-null     category
dtypes: category(1), int64(2)
memory usage: 762.0 bytes

In [17]:
df.age_range.cat.categories

IntervalIndex([  (0, 10],  (10, 20],  (20, 30],  (30, 40],  (40, 50],
                (50, 60],  (60, 70],  (70, 80],  (80, 90], (90, 100]],
              dtype='interval[int64, right]')

In [18]:
# age 컬럼의 값을 사용한 파생변수
df["age_cat"] = pd.cut(x=df.age, bins=[0, 19, 45, 60, 100], right=False,
                       labels=["미성년", "청년", "장년", "노년"])

In [19]:
df

   id  age  age_range age_cat
0   1   93  (90, 100]      노년
1   2   44   (40, 50]      청년
2   3   51   (50, 60]      장년
3   4   26   (20, 30]      청년
4   5   73   (70, 80]      노년
5   6   39   (30, 40]      청년
6   7   87   (80, 90]      노년
7   8   98  (90, 100]      노년
8   9   44   (40, 50]      청년
9  10   70   (60, 70]      노년

In [20]:
df.age_cat.cat.categories

Index(['미성년', '청년', '장년', '노년'], dtype='object')