## DataFrame merge
*   두 개 이상의 dataframe 합쳐서 출력

In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
def set_names():
    names = [
        'akali', 'amumu', 'ashe', 'brand', 'braum',
        'caitlyn', 'darius', 'ekko', 'fiora', 'fiddlesticks',
        'galio', 'garen', 'graves', 'jax', 'jhin',
        'karma', 'kindred', 'leona', 'lulu', 'lux'
    ]
    return random.choice(names)

def set_level(start = 1, end = 18):
    return np.random.randint(start, end + 1)

def datas(n = 20):
    lists = []
    for _ in range(n):
        dic = {
            "Level": set_level(), "Name": set_names()
        }
        lists.append(dic)
    return lists

### dict로 DataFrame 생성

In [3]:
sample1 = {}
sample1["Line"] = ['Top', 'Jungle', 'Mid', 'Bot', 'Sup']
sample1["Level"] = [set_level() for _ in range(5)]
chams = []
while True:
    name = set_names()
    if name not in chams:
        chams.append(name)
    if len(chams) == 5:
        break
sample1['Chams'] = chams

lol_df1 = pd.DataFrame(sample1)
lol_df1

     Line  Level   Chams
0     Top      5    jhin
1  Jungle      6   amumu
2     Mid     18     jax
3     Bot     18   brand
4     Sup      1  graves

### list로 DataFrame 생성

In [4]:
Id = ['Top', 'Jungle', 'Mid', 'Bot', 'Sup']
chams = []
while True:
    name = set_names()
    if name not in chams: chams.append(name)
    if len(chams) == 5: break
level = [set_level() for _ in range(5)]

lol_df2 = pd.DataFrame(columns = ['Line', 'Level', 'Chams'])
for idx in range(5):
    lol_df2.loc[idx] = {"Line": Id[idx], "Level": level[idx], "Chams": chams[idx]}
lol_df2

     Line  Level  Chams
0     Top      9  braum
1  Jungle     18   lulu
2     Mid      4   ashe
3     Bot      1    lux
4     Sup      8  garen

## concat

In [5]:
lol_df = pd.concat([lol_df1, lol_df2], axis = 1)
lol_df

     Line  Level   Chams    Line  Level  Chams
0     Top      5    jhin     Top      9  braum
1  Jungle      6   amumu  Jungle     18   lulu
2     Mid     18     jax     Mid      4   ashe
3     Bot     18   brand     Bot      1    lux
4     Sup      1  graves     Sup      8  garen

## merge

### merge parameters

-   on: 두 데이터프레임에 공통으로 속하는 column을 기준으로 병합
-   how
    -   inner: 기준이 되는 column의 데이터가 양쪽 데이터프레임에 공통으로 존재하는 교집합의 경우
    -   outer: 기준이 되는 column의 데이터가 한쪽에만 존재해도 포함하여 병함
    -   left: 왼쪽 데이터프레임의 기준 column에 속하는 값을 기준으로 병합
    -   right: 오른쪽 데이터프레임의 기준 column에 속하는 값을 기준으로 병합
-   left_on, right_on으로 설정한 기준 column에 how의 옵션 값으로 기준을 결정하여 병합

In [7]:
lol_merge = pd.merge(lol_df1, lol_df2, on = 'Line')
lol_merge.columns = ["Line", "Level", 'Chams', 'Level', 'Chams']
lol_merge

     Line  Level   Chams  Level  Chams
0     Top      5    jhin      9  braum
1  Jungle      6   amumu     18   lulu
2     Mid     18     jax      4   ashe
3     Bot     18   brand      1    lux
4     Sup      1  graves      8  garen

### DataFrame column명 변경

In [8]:
lol_merge.rename(columns = {"Line": "Position"}, inplace = True)
lol_merge

  Position  Level   Chams  Level  Chams
0      Top      5    jhin      9  braum
1   Jungle      6   amumu     18   lulu
2      Mid     18     jax      4   ashe
3      Bot     18   brand      1    lux
4      Sup      1  graves      8  garen

### DataFrame 정렬

In [9]:
lol_merge2 = pd.merge(lol_df1, lol_df2, on = 'Line')
lol_merge2

     Line  Level_x Chams_x  Level_y Chams_y
0     Top        5    jhin        9   braum
1  Jungle        6   amumu       18    lulu
2     Mid       18     jax        4    ashe
3     Bot       18   brand        1     lux
4     Sup        1  graves        8   garen

In [10]:
lol_merge2.sort_values(["Level_x", "Level_y"], ascending = [False, False])

     Line  Level_x Chams_x  Level_y Chams_y
2     Mid       18     jax        4    ashe
3     Bot       18   brand        1     lux
1  Jungle        6   amumu       18    lulu
0     Top        5    jhin        9   braum
4     Sup        1  graves        8   garen

In [11]:
lol_merge3 = lol_df1.merge(lol_df2, on = 'Line')
lol_merge3

     Line  Level_x Chams_x  Level_y Chams_y
0     Top        5    jhin        9   braum
1  Jungle        6   amumu       18    lulu
2     Mid       18     jax        4    ashe
3     Bot       18   brand        1     lux
4     Sup        1  graves        8   garen

In [13]:
lol_merge3.sort_values(['Level_x', 'Level_y'], ascending = [False, True])

     Line  Level_x Chams_x  Level_y Chams_y
3     Bot       18   brand        1     lux
2     Mid       18     jax        4    ashe
1  Jungle        6   amumu       18    lulu
0     Top        5    jhin        9   braum
4     Sup        1  graves        8   garen