# DataFrame 함수

*   head, tail
*   apply

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = {
    "name": ["easyup", "bekko", "Adrian", "Jax"],
    "email": ["support@easyupclass.com", "bekko@easyupclass.com", "adrian@gmail.co", "jax@lol.com"],
    "id": [1, 2, 3, 4]
}
data

{'name': ['easyup', 'bekko', 'Adrian', 'Jax'],
 'email': ['support@easyupclass.com',
  'bekko@easyupclass.com',
  'adrian@gmail.co',
  'jax@lol.com'],
 'id': [1, 2, 3, 4]}

In [ ]:
df = pd.DataFrame(data)
df

     name                    email  id
0  easyup  support@easyupclass.com   1
1   bekko    bekko@easyupclass.com   2
2  Adrian          adrian@gmail.co   3
3     Jax              jax@lol.com   4

## head, tail

In [ ]:
df.head()

     name                    email  id
0  easyup  support@easyupclass.com   1
1   bekko    bekko@easyupclass.com   2
2  Adrian          adrian@gmail.co   3
3     Jax              jax@lol.com   4

In [ ]:
df.head(2)

     name                    email  id
0  easyup  support@easyupclass.com   1
1   bekko    bekko@easyupclass.com   2

In [ ]:
df.tail(2)

     name            email  id
2  Adrian  adrian@gmail.co   3
3     Jax      jax@lol.com   4

## apply

*   map과 유사한 함수

### domain column 생성해보기

In [ ]:
def str_domain(email):
    return email.split("@")[1].split(".")[0]

In [ ]:
str_domain("adrian@gmail.co.kr")

'gmail'

In [ ]:
str_domain(df.loc[1].email)

'easyupclass'

In [ ]:
df['domain'] = df['email'].apply(str_domain)
df

     name                    email  id       domain
0  easyup  support@easyupclass.com   1  easyupclass
1   bekko    bekko@easyupclass.com   2  easyupclass
2  Adrian          adrian@gmail.co   3        gmail
3     Jax              jax@lol.com   4          lol

## 수업용 데이터 생성 함수

In [ ]:
import random

In [ ]:
def set_names():
    names = [
        'akali', 'amumu', 'ashe', 'brand', 'braum',
        'caitlyn', 'darius', 'ekko', 'fiora', 'fiddlesticks',
        'galio', 'garen', 'graves', 'jax', 'jhin',
        'karma', 'kindred', 'leona', 'lulu', 'lux'
    ]
    return random.choice(names)

def set_level(start = 1, end = 18):
    return np.random.randint(start, end + 1)

def datas(n = 20):
    lists = []
    for _ in range(n):
        dic = {
            "Level": set_level(), "Name": set_names()
        }
        lists.append(dic)
    return lists

In [ ]:
df1 = pd.DataFrame(datas(5))
df2 = pd.DataFrame(datas(5))

df1, df2

(   Level     Name
 0     16  caitlyn
 1      1    galio
 2      6     ashe
 3      6      jax
 4     10   darius,
    Level   Name
 0     18  amumu
 1     11   ashe
 2      3   jhin
 3      8  fiora
 4      3    jax)

### DataFrame 합치기

concat

*   row, columm으로 dataframe을 합칠 때 사용

In [ ]:
df3 = pd.concat([df1, df2])
df3

   Level     Name
0     16  caitlyn
1      1    galio
2      6     ashe
3      6      jax
4     10   darius
0     18    amumu
1     11     ashe
2      3     jhin
3      8    fiora
4      3      jax

### index 재정렬

In [ ]:
df3.reset_index(drop = True, inplace = True)
df3

   Level     Name
0     16  caitlyn
1      1    galio
2      6     ashe
3      6      jax
4     10   darius
5     18    amumu
6     11     ashe
7      3     jhin
8      8    fiora
9      3      jax

In [ ]:
df4 = pd.concat([df1, df2]).reset_index(drop = True)
df4

   Level     Name
0     16  caitlyn
1      1    galio
2      6     ashe
3      6      jax
4     10   darius
5     18    amumu
6     11     ashe
7      3     jhin
8      8    fiora
9      3      jax

In [ ]:
pd.concat([df1, df2], axis = 1)

   Level     Name  Level   Name
0     16  caitlyn     18  amumu
1      1    galio     11   ashe
2      6     ashe      3   jhin
3      6      jax      8  fiora
4     10   darius      3    jax

### group by

*   특정 컬럼의 중복되는 데이터를 합쳐서 새로운 dataframe을 생성

In [ ]:
df5 = pd.DataFrame(datas())
df5

    Level          Name
0      13          lulu
1      15         fiora
2      14          lulu
3      13  fiddlesticks
4       5         galio
5      10       kindred
6       1         akali
7      14         leona
8      13         garen
9       2         leona
10     16       kindred
11      1         garen
12     17        darius
13     16         karma
14      4          ashe
15      9       caitlyn
16      2         galio
17      5       kindred
18     13         karma
19      7         fiora

### size

In [ ]:
res = df5.groupby("Name").size().reset_index(name = "counts")
res

            Name  counts
0          akali       1
1           ashe       1
2        caitlyn       1
3         darius       1
4   fiddlesticks       1
5          fiora       2
6          galio       2
7          garen       2
8          karma       2
9        kindred       3
10         leona       2
11          lulu       2

### sort_values: 설정값으로 column 정렬

In [ ]:
res2 = res.sort_values(['counts'], ascending = False).reset_index(drop = True)
res2

            Name  counts
0        kindred       3
1          galio       2
2          fiora       2
3          garen       2
4          leona       2
5          karma       2
6           lulu       2
7          akali       1
8         darius       1
9        caitlyn       1
10          ashe       1
11  fiddlesticks       1

### agg
*   파라미터로 'max', 'min', 'mean' 등을 사용

In [ ]:
df5.groupby("Name").agg("min").reset_index()

            Name  Level
0          akali      1
1           ashe      4
2        caitlyn      9
3         darius     17
4   fiddlesticks     13
5          fiora      7
6          galio      2
7          garen      1
8          karma     13
9        kindred      5
10         leona      2
11          lulu     13

In [ ]:
df5.sort_values("Name")

    Level          Name
6       1         akali
14      4          ashe
15      9       caitlyn
12     17        darius
3      13  fiddlesticks
19      7         fiora
1      15         fiora
4       5         galio
16      2         galio
8      13         garen
11      1         garen
18     13         karma
13     16         karma
17      5       kindred
5      10       kindred
10     16       kindred
9       2         leona
7      14         leona
2      14          lulu
0      13          lulu

### DataFrame 요약보기

In [ ]:
df5.describe()

           Level
count  20.000000
mean    9.500000
std     5.596051
min     1.000000
25%     4.750000
50%    11.500000
75%    14.000000
max    17.000000

In [ ]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Level   20 non-null     int64
 1   Name    20 non-null     object
dtypes: int64(1), object(1)
memory usage: 452.0+ bytes