# DataFrame

*   여러개의 Series로 구성

## 생성

### dict안에 list로 value 생성`

In [16]:
data = {
    "name": ["easyup", "python"],
    "class": ["open", "open2"]
}
data

{'name': ['easyup', 'python'], 'class': ['open', 'open2']}

In [17]:
import pandas as pd
import numpy as np

In [18]:
df = pd.DataFrame(data)
df

     name  class
0  easyup   open
1  python  open2

In [19]:
print(df)

     name  class
0  easyup   open
1  python  open2

### list안에 dict 생성

In [20]:
data2 = [{"name": "easyup", "class": "open"},
         {"name": "python", "class": "open2"}]
data2

[{'name': 'easyup', 'class': 'open'}, {'name': 'python', 'class': 'open2'}]

In [21]:
df2 = pd.DataFrame(data2)
df2

     name  class
0  easyup   open
1  python  open2

- python 버전별로 pandas에 데이터 컬럼이 생성되는 순서가 변경됨

### index 추가

In [22]:
df

     name  class
0  easyup   open
1  python  open2

In [23]:
df3 = pd.DataFrame(data, index = ["a", "b"])
df3

     name  class
a  easyup   open
b  python  open2

In [24]:
df3.index

Index(['a', 'b'], dtype='object')

In [25]:
df3.values

array([['easyup', 'open'],
       ['python', 'open2']], dtype=object)

### index 변경

In [26]:
df3

     name  class
a  easyup   open
b  python  open2

In [27]:
df

     name  class
0  easyup   open
1  python  open2

In [28]:
df.index = ["1번", "2번"]
df

      name  class
1번  easyup   open
2번  python  open2

## DataFrame data 선택

*   row, column 선택 방법

### row 선택

In [29]:
df

      name  class
1번  easyup   open
2번  python  open2

In [32]:
df.loc[0]

KeyError: 0

In [33]:
df.loc["1번"]

name     easyup
class      open
Name: 1번, dtype: object

### row 선택 후 특정 컬럼 선택

In [34]:
df.loc["1번"]["class"]

'open'

### loc로 dataframe에 데이터 추가

In [35]:
df.loc["3번"] = {"name": "Adrian", "class": "math"}
df

      name  class
1번  easyup   open
2번  python  open2
3번  Adrian   math

## column 선택

In [36]:
df['name']

1번    easyup
2번    python
3번    Adrian
Name: name, dtype: object

### DataFrame에서 column 리스트 확인

In [37]:
df.index

Index(['1번', '2번', '3번'], dtype='object')

In [38]:
df.columns

Index(['name', 'class'], dtype='object')

In [39]:
list(df.columns)

['name', 'class']

### column 추가

In [40]:
df['age'] = [20, 1, 25]
df

      name  class  age
1번  easyup   open   20
2번  python  open2    1
3번  Adrian   math   25

In [41]:
df.dtypes

name     object
class    object
age       int64
dtype: object

### row, column 선택

In [42]:
df

      name  class  age
1번  easyup   open   20
2번  python  open2    1
3번  Adrian   math   25

In [43]:
df.loc[["3번"], ['class', 'age']]

   class  age
3번  math   25

In [44]:
df.loc[["2번", "3번"], ["name"]]

      name
2번  python
3번  Adrian

### dataframe 조건으로 선택

In [45]:
df

      name  class  age
1번  easyup   open   20
2번  python  open2    1
3번  Adrian   math   25

In [46]:
df[df['age'] > 20]

      name class  age
3번  Adrian  math   25

### DataFrame row, column 삭제

*   drop() 메소드 이용

In [47]:
df.drop(index = "3번")

      name  class  age
1번  easyup   open   20
2번  python  open2    1

In [48]:
df.drop(columns = 'age')

      name  class
1번  easyup   open
2번  python  open2
3번  Adrian   math

In [49]:
df

      name  class  age
1번  easyup   open   20
2번  python  open2    1
3번  Adrian   math   25

In [50]:
df.drop(index = "3번", columns = 'age', inplace = True)

In [51]:
df

      name  class
1번  easyup   open
2번  python  open2