In [1]:
import pandas as pd
import numpy as np

# pivot

-   index, column, value를 선택해서 DataFrame 생성

df.pivot(index, column, values)


df.pivot_table(values, index, colums, aggfunc)

In [6]:
tit = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/titanic.csv", sep = '\t')
tit

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## Sex, Pclass 에 따른 데이터 수

In [9]:
tit_df = tit.groupby(["Sex", "Pclass"]).size().reset_index(name = "counts")
tit_df

      Sex  Pclass  counts
0  female       1      94
1  female       2      76
2  female       3     144
3    male       1     122
4    male       2     108
5    male       3     347

In [11]:
res1 = tit_df.pivot(index = "Sex", columns = "Pclass", values = "counts")
res1

Pclass    1    2    3
Sex
female   94   76  144
male    122  108  347

In [12]:
tit["Counts"] = 1
tit

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Counts
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,1
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1

In [15]:
res2 = tit.pivot_table("Counts", "Sex", "Survived", aggfunc = np.sum)
res2

/tmp/ipython-input-2184384231.py:1: FutureWarning: The provided callable <function sum at 0x7fab993427a0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  res2 = tit.pivot_table("Counts", "Sex", "Survived", aggfunc = np.sum)

Survived    0    1
Sex
female     81  233
male      468  109

In [17]:
res3 = tit.pivot_table("Counts", ["Pclass"], ["Survived"], aggfunc=np.sum)
res3

/tmp/ipython-input-1135351083.py:1: FutureWarning: The provided callable <function sum at 0x7fab993427a0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  res3 = tit.pivot_table("Counts", ["Pclass"], ["Survived"], aggfunc=np.sum)

Survived    0    1
Pclass
1          80  136
2          97   87
3         372  119

In [18]:
res3["Total1"] = res3[0] + res3[1]
res3

Survived    0    1  Total1
Pclass
1          80  136     216
2          97   87     184
3         372  119     491

In [19]:
res3.loc["Total"] = res3.loc[1] + res3.loc[2] + res3.loc[3]
res3  # iloc[]와 다름.

Survived    0    1  Total1
Pclass
1          80  136     216
2          97   87     184
3         372  119     491
Total     549  342     891