# Practice

-   임의의 DataFrame 생성
-   월간 주식 수익률 데이터프레임 생성 후 agg() 함수로 분석

In [1]:
import pandas as pd
import numpy as np
dates = pd.date_range(start = "20200101", end = '20201201', freq = 'MS')
dates = pd.Series(dates, name = 'Date')
dates

0    2020-01-01
1    2020-02-01
2    2020-03-01
3    2020-04-01
4    2020-05-01
5    2020-06-01
6    2020-07-01
7    2020-08-01
8    2020-09-01
9    2020-10-01
10   2020-11-01
11   2020-12-01
Name: Date, dtype: datetime64[ns]

In [2]:
values = np.array([round(np.random.normal(0., 5.,), 2) for _ in range(48)]).reshape(12, -1)
values = pd.DataFrame(values, columns = list('Chocopie Miz Kid-0 Diget'.split(" ")))
values

    Chocopie   Miz  Kid-0  Diget
0      -4.63 -2.97   1.45  -0.64
1       6.67 -0.41  -0.35  -4.59
2       2.11  5.62  -2.22  -2.71
3       8.59  2.49   2.34   5.25
4      -0.18  4.38   3.40   1.30
5     -10.38 -2.56   1.95   1.56
6       2.32 -4.73   3.35   7.52
7      -0.74  3.47   3.00  -1.79
8      -4.96  2.59   0.81   2.82
9      -5.57 -1.39   3.12   4.18
10     -7.70 -0.79   7.40   0.25
11      7.67 -4.61  -0.88   5.67

In [3]:
stock_df = pd.concat([dates, values], axis = 1)
stock_df

         Date  Chocopie   Miz  Kid-0  Diget
0  2020-01-01     -4.63 -2.97   1.45  -0.64
1  2020-02-01      6.67 -0.41  -0.35  -4.59
2  2020-03-01      2.11  5.62  -2.22  -2.71
3  2020-04-01      8.59  2.49   2.34   5.25
4  2020-05-01     -0.18  4.38   3.40   1.30
5  2020-06-01    -10.38 -2.56   1.95   1.56
6  2020-07-01      2.32 -4.73   3.35   7.52
7  2020-08-01     -0.74  3.47   3.00  -1.79
8  2020-09-01     -4.96  2.59   0.81   2.82
9  2020-10-01     -5.57 -1.39   3.12   4.18
10 2020-11-01     -7.70 -0.79   7.40   0.25
11 2020-12-01      7.67 -4.61  -0.88   5.67

In [4]:
stock_df1 = stock_df[['Chocopie', 'Miz', 'Kid-0', 'Diget']]
stock_df1

    Chocopie   Miz  Kid-0  Diget
0      -4.63 -2.97   1.45  -0.64
1       6.67 -0.41  -0.35  -4.59
2       2.11  5.62  -2.22  -2.71
3       8.59  2.49   2.34   5.25
4      -0.18  4.38   3.40   1.30
5     -10.38 -2.56   1.95   1.56
6       2.32 -4.73   3.35   7.52
7      -0.74  3.47   3.00  -1.79
8      -4.96  2.59   0.81   2.82
9      -5.57 -1.39   3.12   4.18
10     -7.70 -0.79   7.40   0.25
11      7.67 -4.61  -0.88   5.67

## 그룹함수 직접 구현하기

In [5]:
stock_df1.describe()

        Chocopie        Miz      Kid-0      Diget
count  12.000000  12.000000  12.000000  12.000000
mean   -0.566667   0.090833   1.947500   1.568333
std     6.236002   3.533511   2.497741   3.672782
min   -10.380000  -4.730000  -2.220000  -4.590000
25%    -5.112500  -2.662500   0.520000  -0.927500
50%    -0.460000  -0.600000   2.145000   1.430000
75%     3.407500   2.810000   3.177500   4.447500
max     8.590000   5.620000   7.400000   7.520000

In [6]:
pd.DataFrame({'Sum': stock_df1.agg('sum'),
              "Mean": round(stock_df1.agg('mean'), 2),
              'Min': stock_df1.agg('min'),
              'Max': stock_df1.agg('max')}).T

      Chocopie   Miz  Kid-0  Diget
Sum      -6.80  1.09  23.37  18.82
Mean     -0.57  0.09   1.95   1.57
Min     -10.38 -4.73  -2.22  -4.59
Max       8.59  5.62   7.40   7.52

## 결측치 채우기

### 결측 데이터 생성

In [9]:
couque_date = pd.to_datetime(['2020-01-01', '2020-02-01', '2020-04-01', '2020-06-01', '2020-07-01', '2020-10-01', '2020-12-01'])
couque_date = pd.Series(couque_date, name = 'Date')
couque_date

0   2020-01-01
1   2020-02-01
2   2020-04-01
3   2020-06-01
4   2020-07-01
5   2020-10-01
6   2020-12-01
Name: Date, dtype: datetime64[ns]

In [13]:
couque_rev = pd.Series([round(np.random.normal(0., 5.,), 2) for _ in range(len(couque_date))], name = "Couque D'asse")
couque_df = pd.concat([couque_date, couque_rev], axis = 1)
couque_df

        Date  Couque D'asse
0 2020-01-01           8.86
1 2020-02-01           9.31
2 2020-04-01           3.84
3 2020-06-01          -7.78
4 2020-07-01           3.69
5 2020-10-01           1.29
6 2020-12-01          -0.90

In [14]:
stock_df

         Date  Chocopie   Miz  Kid-0  Diget
0  2020-01-01     -4.63 -2.97   1.45  -0.64
1  2020-02-01      6.67 -0.41  -0.35  -4.59
2  2020-03-01      2.11  5.62  -2.22  -2.71
3  2020-04-01      8.59  2.49   2.34   5.25
4  2020-05-01     -0.18  4.38   3.40   1.30
5  2020-06-01    -10.38 -2.56   1.95   1.56
6  2020-07-01      2.32 -4.73   3.35   7.52
7  2020-08-01     -0.74  3.47   3.00  -1.79
8  2020-09-01     -4.96  2.59   0.81   2.82
9  2020-10-01     -5.57 -1.39   3.12   4.18
10 2020-11-01     -7.70 -0.79   7.40   0.25
11 2020-12-01      7.67 -4.61  -0.88   5.67

In [15]:
stock_df2 = pd.merge(stock_df, couque_df, how = 'outer')
stock_df2

         Date  Chocopie   Miz  Kid-0  Diget  Couque D'asse
0  2020-01-01     -4.63 -2.97   1.45  -0.64           8.86
1  2020-02-01      6.67 -0.41  -0.35  -4.59           9.31
2  2020-03-01      2.11  5.62  -2.22  -2.71            NaN
3  2020-04-01      8.59  2.49   2.34   5.25           3.84
4  2020-05-01     -0.18  4.38   3.40   1.30            NaN
5  2020-06-01    -10.38 -2.56   1.95   1.56          -7.78
6  2020-07-01      2.32 -4.73   3.35   7.52           3.69
7  2020-08-01     -0.74  3.47   3.00  -1.79            NaN
8  2020-09-01     -4.96  2.59   0.81   2.82            NaN
9  2020-10-01     -5.57 -1.39   3.12   4.18           1.29
10 2020-11-01     -7.70 -0.79   7.40   0.25            NaN
11 2020-12-01      7.67 -4.61  -0.88   5.67          -0.90

In [17]:
stock_df2.index = stock_df2["Date"]
stock_df2.drop("Date", axis = 1, inplace=True)
stock_df2

            Chocopie   Miz  Kid-0  Diget  Couque D'asse
Date
2020-01-01     -4.63 -2.97   1.45  -0.64           8.86
2020-02-01      6.67 -0.41  -0.35  -4.59           9.31
2020-03-01      2.11  5.62  -2.22  -2.71            NaN
2020-04-01      8.59  2.49   2.34   5.25           3.84
2020-05-01     -0.18  4.38   3.40   1.30            NaN
2020-06-01    -10.38 -2.56   1.95   1.56          -7.78
2020-07-01      2.32 -4.73   3.35   7.52           3.69
2020-08-01     -0.74  3.47   3.00  -1.79            NaN
2020-09-01     -4.96  2.59   0.81   2.82            NaN
2020-10-01     -5.57 -1.39   3.12   4.18           1.29
2020-11-01     -7.70 -0.79   7.40   0.25            NaN
2020-12-01      7.67 -4.61  -0.88   5.67          -0.90

In [18]:
stock_df2.fillna(stock_df2["Couque D'asse"].mean(), inplace=True)
stock_df2

            Chocopie   Miz  Kid-0  Diget  Couque D'asse
Date
2020-01-01     -4.63 -2.97   1.45  -0.64       8.860000
2020-02-01      6.67 -0.41  -0.35  -4.59       9.310000
2020-03-01      2.11  5.62  -2.22  -2.71       2.615714
2020-04-01      8.59  2.49   2.34   5.25       3.840000
2020-05-01     -0.18  4.38   3.40   1.30       2.615714
2020-06-01    -10.38 -2.56   1.95   1.56      -7.780000
2020-07-01      2.32 -4.73   3.35   7.52       3.690000
2020-08-01     -0.74  3.47   3.00  -1.79       2.615714
2020-09-01     -4.96  2.59   0.81   2.82       2.615714
2020-10-01     -5.57 -1.39   3.12   4.18       1.290000
2020-11-01     -7.70 -0.79   7.40   0.25       2.615714
2020-12-01      7.67 -4.61  -0.88   5.67      -0.900000

In [19]:
pd.options.display.float_format = '{:.2f}'.format
stock_df2

            Chocopie   Miz  Kid-0  Diget  Couque D'asse
Date
2020-01-01     -4.63 -2.97   1.45  -0.64           8.86
2020-02-01      6.67 -0.41  -0.35  -4.59           9.31
2020-03-01      2.11  5.62  -2.22  -2.71           2.62
2020-04-01      8.59  2.49   2.34   5.25           3.84
2020-05-01     -0.18  4.38   3.40   1.30           2.62
2020-06-01    -10.38 -2.56   1.95   1.56          -7.78
2020-07-01      2.32 -4.73   3.35   7.52           3.69
2020-08-01     -0.74  3.47   3.00  -1.79           2.62
2020-09-01     -4.96  2.59   0.81   2.82           2.62
2020-10-01     -5.57 -1.39   3.12   4.18           1.29
2020-11-01     -7.70 -0.79   7.40   0.25           2.62
2020-12-01      7.67 -4.61  -0.88   5.67          -0.90

In [20]:
stock_df2.describe()

       Chocopie   Miz  Kid-0  Diget  Couque D'asse
count     12.00 12.00  12.00  12.00          12.00
mean      -0.57  0.09   1.95   1.57           2.62
std        6.24  3.53   2.50   3.67           4.36
min      -10.38 -4.73  -2.22  -4.59          -7.78
25%       -5.11 -2.66   0.52  -0.93           2.28
50%       -0.46 -0.60   2.15   1.43           2.62
75%        3.41  2.81   3.18   4.45           3.73
max        8.59  5.62   7.40   7.52           9.31

In [21]:
pd.DataFrame({'Sum': stock_df2.agg('sum'),
              "Mean": stock_df2.agg('mean'),
              'Min': stock_df2.agg('min'),
              'Max': stock_df2.agg('max')}).T

      Chocopie   Miz  Kid-0  Diget  Couque D'asse
Sum      -6.80  1.09  23.37  18.82          31.39
Mean     -0.57  0.09   1.95   1.57           2.62
Min     -10.38 -4.73  -2.22  -4.59          -7.78
Max       8.59  5.62   7.40   7.52           9.31